name: 16 - Working with Environments

on:
  workflow_dispatch:
    inputs:
      target-env: 
        type: environment
        efault: staging

jobs:
   echo:
       runs-on: ubuntu-latest
       environment: ${{ inputs.target-env }}
       env:
           my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
       steps:
         - name: Echo vars
           run: |
            echo "Env variable: ${{ vars.my-env-value }}"


  