name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS

on:
  workflow_dispatch:
    
env:
    working-directory: 17-custom-actions/react-app

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Check for dependency updtates
            uses: ./.github/actions/js-dependency-update
           